pmsf/PMSF

- README.md
- cleandb.sql
could also be used if on RM or other previous systems , start with fresh and then migrate data into this blank DB
> clean db for folks just starting out

- static/js/map.js
> New layer for ingress portals

- config/example.access-config.php
sets 2 more levels by default and adds more configuration options
> expand example.access-config.php

- lib/RDM.php
- static/js/map.common.js
> jitter fix

- static/data/pokemon.json
Fix typing for Turtwig and Chimchar family
> Fix typing for Turtwig and Chimchar family

- lib/search/Search.rdm.php
this fixes stop images from not showing up on mobile. now does someone want to fix the bug where it doesn't scroll?
> fix stop images on quest search

- static/js/map.common.js
- static/js/map.js
With these changes, every marker will be hidden, if it's not inside the current view. 
This increases performance since any kind of zoom or drag won't cause marker positions getting updated.
> Improve map performance by hiding markers being out of view

- lib/Monocle.php
- lib/Monocle_MAD.php
Height select seems to be left off from Monocle_MAD
> MAD Monocle supports height

- user.php
The current e-mail encoding has problems with german special chars.
> change mail encoding

- config/default.php
- config/example.config.php
- pre-index.php
- static/js/map.js
[x] Includes default.php, example.config.php changes
Feature for multiple iconpacks, based on 2 new config options.
First is to turn the feature on/off, second is to define the multiple packs in an array with names so users can select their wished pack.
Tested locally, but since im not a git brain i may missed something.
> Added multiple iconpack feature

- static/js/map.js
- static/locales/de.json
Added tooltips for 3 icons + despawntimer icon. German translation included :)
> Add tooltips for pokemon label

- static/data/mapstyle.json
- static/js/map.js
Dynamic pgo map style, this will change between Mapbox pgoday and Mapbox pgodark depending on client time. I tested it for a few morning and nights works well.
> I hope I did this right.

- config/example.config.php
- pre-index.php
Add config option to force login with native login or discord login
> forcedLogin

- lib/RDM.php
requires https://github.com/RealDeviceMap/RealDeviceMap/pull/46
> rdm raid costumes

- static/data/pokemon.json
github editor sucks, that last line ending might have to be fixed before merge :o
> Fix Galarian Farfetch'd form

- pre-index.php
With the addition of Dark Mode toggle if all other settings are disabled besides dark mode toggle the Style Accordian breaks. This 2 line addition will resolve the issue.
> Fix Layout Issue

- static/js/map.js
Title says it all.
I tested it locally and it works like a charm.
> Show pokemon level in notification

- pre-index.php
Added Option 6 for Min/Max Filter and the Notify filter
Also added the option into the manual quest section for future proofing
> Min/Max & Notify Mega

- static/locales/de.json
> fix german typo

- lib/RDM.php
also seems to fix pokestops showing up when you scroll around the map
> fix "number of bound variables does not match number of tokens" error

- config/default.php
- lib/submit/Submit.rocketmap_mad.php
add pokestop and gym delete functions for mad
> Mad delete functions

- pre-index.php
- register.php
- static/sass/layout/_login.scss
- utils.php
Better error handling for Native Auth
Better id picker for Native Auth and bug fix.
Minor styling
> More native code and better id picker

- static/js/vendor/Leaflet.GoogleMutant.js
the current used version of GoogleMutant is causing some race conditions especially on desktop mode. This hopefully fixes the issue of google map layers never loading up, and "clear all cookies" is the only escape.
> Update Leaflet.GoogleMutant.js to latest

- static/data/grunttype.json
Don't see this on Reddit, so basing it on the 400 Grunts I've done in the past couple days. Pretty sure it's right...
> New Grunt Rewards...but with 4k+ fewer changes!!!

- static/data/grunttype.json
now i'm unsure what willem did with my last PR but here it is, hopefully correct this time. pliny had some rewards different from my version.
> correct grunttypes

- login.php
Untested but feels like a copy/paste error that should have been like this: https://github.com/pmsf/PMSF/blob/develop/pre-index.php#L1685
> Correct value for the `Login with facebook` button?

- static/js/map.js
- static/sass/components/_button.scss
Adds a copy coords button to pokemon, stops, and gyms. Not POIs since I have those turned off and didn't test. 
Respects "hidePokemonCoords" settings, of course.
> add copy coords button

- static/js/map.js
> Revert "Partially refactored `clearStaleMarkers` to make clearing Pokemon readable"

- static/js/map.js
> Revert "Credits to alexameen PR408"

- lib/RDM.php
https://github.com/pmsf/PMSF/pull/430
> fix misplaced >= from PR430

- pre-index.php
- static/sass/components/_form.scss
- static/sass/layout/_dark.scss
- static/sass/layout/_nav.scss
- static/sass/layout/_stats.scss
> fixes css with the introduction of bootstrap

- static/data/conditiontype.json
- static/data/items.json
- static/data/moves.json
- static/data/pokemon.json
- static/data/questtype.json
- static/data/rewardtype.json
Updated the static/data/ JSON files for missing entries like pokemon/forms, items, moves, and quest info.
> JSON Updates for Missing Entries

- config/default.php
- static/data/moves.json
- static/data/pokemon.json
i think that's all that's needed.
> quick gen 8 update ($numberOfPokemon, moves.json & pokemon.json)

- pre-index.php
> Revert "Staging -> Develop"

- static/data/grunttype.json
#568 had some errors. this version is generated from the game files and should be accurate.
> Update grunttype.json (autogenerated)

- config/default.php
- config/example.config.php
- static/data/grunttype.json
- static/data/moves.json
Update moves.json 
- Add move 365 (Luster Purge)
Update grunttype.json
- Update current lineup
- Add Event NPC 11-20 (id 514 to 523)
> Update moves.json and grunttype.json

- static/data/moves.json
- static/data/pokemon.json
- Add move 366 (Mist Ball)
- Update forms from 0.233 protos
> Updates moves.json & pokemon.json

- static/data/moves.json
- Add move 367 (Brutal Swing) and 368 (Rollout)
> Updates moves.json

- package.json
- rdm pvp 2.0 support
- rdm multi invasion support
- package version update: node-sass + moment
> develop -> staging

- lib/stats/Stats.rdm.php
- leftover `incident_expire_timestamp` that couldn't handle new rdm db structure
> fix stats overview (rdm)

- static/data/grunttype.json
- static/data/moves.json
> json: add move 369 (Seed Flare) and update grunts

- config/default.php
- config/example.config.php
- filterimages.php
- static/data/pokemon.json
- static/data/questtype.json
- pokemon.json
- questtype.json
> json update + push max pokemon to 905

- static/data/questtype.json
- `QUEST_BATTLE_EVENT_NPC` = `Battle {0} Challenger(s)`
> update quest type 55 text

- lib/RDM.php
- lib/stats/Stats.rdm.php
> fix: query could fail when `ONLY_FULL_GROUP_BY` sql_mode was enabled.

- lib/RDM.php
- lib/RocketMap.php
- lib/RocketMap_MAD.php
- lib/search/Search.rdm.php
- add missing indent spaces
- remove extra spaces and lines
- convert rest of `$ar_string` to curly
- etc
> code cleanup and formatting

- logout.php
- `PHP message: PHP Notice:  Undefined index: reason`
> logout: check `$_GET['reason']` is set before comparison

- static/js/map.js
Black on green text was too unreadable.
> Change Pokemon Toast Header from Green To Yellow

- lib/RDM.php
- rdm renamed the column (see rdm pr 456)
> rdm: add compatibility for size or height column (pokemon)

- static/data/grunttype.json
- static/data/pokemon.json
- static/js/map.js
- Send {0} Gift(s) *with a sticker*
- Catch {0} *different species of* Pokémon
> update json + add more quest condition types

- lib/RocketMap_MAD.php
Kecleon detection had parenthesis at the wrong spot. I moved it.
> Fix Event detection for  Kecleon

- lib/RDM.php
- lib/RocketMap_MAD.php
- static/js/map.js
> add mons size to popup

- lib/RDM.php
- lib/RocketMap_MAD.php
- lib/Scanner.php
- lib/stats/Stats.php
- `$pokemonSizeArray` was identical in both backend = duplicate code = belongs in `Scanner.php`
- add missing declaration for $items and $grunttype in `Scanner.php` and `Stats.php`
> code cleanup

- lib/RDM.php
- lib/RocketMap_MAD.php
- lib/stats/Stats.rocketmap_mad.php
- both mad master and async branches should work.
- same as rdm: only 1 invasion (lowest id) and event per stop.
- rdm+mad: tweak logic
> mad async `pokestop_incident` table support

- Dockerfile
- php will also need to be bumped but Facebook currently incompatible with 8.x
> update Dockerfile to node 16

- lib/RocketMap_MAD.php
- if you scan both layers: `$noQuestsARTaskToggle = false;`
> mad: support async quest layers

- static/data/grunttype.json
- static/data/pokemon.json
> json updates

- pre-index.php
Chrome was complaining, and this resolved the errors.
> Fix labels inside pre-index.php

- lib/Golbat.php
- raw_data.php
- there is no device information in Golbat's database.
> golbat: always returns null for scanner location

- composer.json
- config/default.php
- config/example.config.php
- lib/Golbat.php
- lib/search/Search.golbat.php
- raw_data.php
- composer.json has been updated -> `composer update`.
- full stats not implemented
> add golbat api for pokemons
