pmsf/PMSF

- static/data/quests.json
- static/data/rewards.json
as per title, added Girafarig to rewards and quests Catch 10 Psychic-type Pokémon, Evolve 3 Slowpoke or Exeggcute, Catch 5 Abra or Drowzee --> Jynx (seen a lot)
As per Reddit post https://www.reddit.com/r/TheSilphRoad/comments/9lpqud/psychic_event_field_research_mega_thread/ no removal of quests necessary
> Psychic event quests/rewards update

- lib/RDM.php
My raid-eggs show up as ?? until the page is refreshed, and I traced this back to the RDM-scanner being slower then the time-frame that raw_data is looking for changes.
Example;
The egg is hatched at 13:01, but my scanner scanned the egg first 13:05, the last_modified_timestamp will say 13:01, so the change won't be acknowledged because its "too old". Setting the value for when the record was updated by RDM remedies this and the updated egg (hatch) is sent.
Downside;
More data will be sent because the gyms-json array will be populated even when no "real" update has happened, since RDM updates when it last scanned, regardless if any data in the gym changed.
_In my opinion_ the added network data is negligible.
Perhaps another way would be to use a different time frame for looking for …
> RDM: Use updated value from rdm instead of proto-value

- static/js/map.js
Add support to use default geojson.io stroke and fill colors instead of everything being blue.
> Add support for geojson.io stroke and fill colors

- lib/search/Search.monocle_mad.php
- lib/search/Search.monocle_pmsf.php
- lib/search/Search.rdm.php
- lib/search/Search.rocketmap_mad.php
- static/js/map.js
**AS LONG AS THE QUERIES IN THE LATEST DEVELOP ARE CORRECT, THIS WILL POPULATE THE FORM VARIABLE PROPERLY BUT IT NEEDS TO BE TESTED/CONFIRMED WORKING BEFORE MERGE.**
**CONFIRM WORKING**: MAD(RocketMap db)
**UNCONFIRMED**: Monocle db and RDM db
Reward searches were not querying the database for the form value and the frontend was using a static `_00` to display the images. This is mainly the same fix I have been using in my fork for a while.
Reusing the queries available in the latest develop branch, it’ll now fetch the information and put the value in `quest_pokemon_formid` since that’s the name used for the regular stops queries for the same purpose.
The frontend is modified to use that value in exactly the same way used for the pokéstop display.
> WIP: Reward Search: Add Pokémon Form Images

- lib/Monocle_MAD.php
- lib/Monocle_PMSF.php
- lib/RDM.php
- lib/RocketMap_MAD.php
The frontend map.js was already looking for the information in this element's name (`var raidForm = item['form']`) so this PR simply fills it with the proper value when the database is queried and no changes to map.js are required.
It is the same fix I have been using in my fork but cleaned up without unnecessary changes and should work with all supported backend variants reusing the information and queries available in the latest develop branch.
NOTE: This does NOT add form images to the reward searches which will be handled in a separate PR.
> Add Pokémon Forms Images to Gym/Raid Icons and Sidebar.

- discord-callback.php
Don't redirect back to discord-auth after we failed to login because of an exception. 
Also log the exception into the errorlog for debugging
> Log discord loginexception

- lib/RocketMap_MAD.php
- static/js/map.js
INFO:
MAD's `calc_endminsec` format is either `null` (unverified) or `MM:SS` (verified) representing the despawn minute and second.
BUG:
`expire_timestamp_verified` is currently assigned using `floatval($pokemon["expire_timestamp_verified"])` which, on a value of 00:17, results in a value of `0` which is later interpreted as unverified (wrong).
FIX:
The actual value doesn't appear to used for anything so assigning a value of `1` (or higher) if verified and `null` (or 0) if unverified solves the issue while remaining compatible with the current logic in `map.js` and without adding a special condition.
> FiX: MAD Verified/Unverified.

- lib/search/Search.monocle_pmsf.php
- lib/search/Search.rdm.php
- lib/search/Search.rocketmap_mad.php
Boundaries were not applied to anything except for rewards in the magnifying glass search. This update will apply boundaries to the gym/pokestop/nest/portal searches also.
Tested this on RDM with the gym and pokestop changes. I did not test nests and portals or on MAD.
> Apply Boundaries

- pre-index.php
don't display expire timestamp for discord users if you're running discord and native login concurrently.
> don't confuse discord users

- pre-index.php
- static/js/map.js
Adds a new direction provider: geo uri.
What is it? 
instead of linking to google maps direction it links to a `geo:lat,lon` link. This link will (on Android phones) allow the user to select their map app of choice at the time of clicking the link.
Example:
Unfortunately this uri scheme does not seem to be supported on iOS at this time, but it's a cool feature in any case.
> Geo uri support

- static/data/pokemon.json
Niantic uses the same form numbers for both Nidoran genders.
> Add Nidoran male forms

- static/js/map.js
MAD doesn't have a `level` key and displays `undefined` for the level in the notification window.
Simply compute the level from the `cp_multiplier` like everywhere else to fix the issue
> MAD: level key doesn't exist = undefined. Compute from cp_multiplier

- static/js/map.js
MAD doesn't have a `level` key so it could never trigger. This simply adds the MAD condition and proper level compute for both platforms.
> MAD Fix: `Notify of Level` could never trigger

- sql/manualdb/update13_manualdb.sql
My nestscript fork will require a different table structure. this PR adds an update sql file.
It's only removing the `nest_submitted_by` columns which is neither being used by PMSF nor by madaos script. So it should be compatible
> Changing the nest table format

- static/js/map.js
Makes `clearStaleMarkers` significantly more readable.
Several instances of `new Date().getTime()` were combined into a variable to reduce overhead.
I am unable to test these changes because I do not have RDM/Rocketmap.
I was as careful as possible while writing this, but someone should sanity check it against a test environment.
> Partially refactored `clearStaleMarkers` to make clearing Pokemon readable

- lib/RDM.php
- lib/RocketMap_MAD.php
nginx's error log full of: `PHP Notice:  Undefined variable: noInBattle in /xxxxxxxxxxxxxxxxxxx/RocketMap_MAD.php on line 414`.
> Fix $noInBattle variable's scope issue

- static/js/map.js
For Safari users, there was a race condition preventing the map from fully loading, especially the sidebar. The results of this were the side menu tabs appearing as links instead of intended tabs. More importantly, settings were not being saved to the users' localStorage if a user were to attempt to change a setting when the race condition has hit the failed path.
Test:
Open the map using Safari, either on iOS or desktop. Keep notice of the side menu tabs. If they appear as links, you've hit the bug. If you keep refreshing, you'll see that it'll eventually render as tabs.
> Fixed map load race condition affecting Safari browsers.

- static/js/map.js
**DEVS:**
I've been using this since late 2019 without issues. If you feel there is a better way to do it, feel free to do it!
**ISSUE:**
Stock pmsf will not update a mons marker after it has been processed once even if the 1st time was without encounter data and the 2nd time would have added the encounter data. The only way to display the encounter data in that case is to reload the entire map or disable/enable mons which is not practical. This also means a end-user won't know of a 100% if it was processed before without the encounter data.
**WHAT THIS DOES:**
This will compare the previously processed mons to the new received data and, if it would add the encounter information, it simply delete the previous information continues as if it was a new mons to ensure proper notifications and …
> Don't skip encounter data on previously processed mons without encounter data

- login.php
I've been using this for a little while without complaints but extra testing / validation with another pair of eyes would be welcome.  This hopefully solves the "blacklist warning" that is randomly popping up for users. If not, we'll have to also validate the received Discord data.
**Changes:**
- Make sure that Discord API requests are completed successfully (code 200) otherwise redirect to a new error message. User validation is now only attempted if all Discord API requests are successful.
- Only check `$guild->id` if the value is not empty() in case Discord doesn't return valid data. This should also prevent a match against an empty $serverBlacklist and redirection to a wrong error message for the user ("you are in a blacklisted server").
NOTE: While code 204 (the request completed …
> Add some validation during Discord login

- config/default.php
- config/example.config.php
- lib/Monocle.php
- lib/Monocle_PMSF.php
- lib/RDM.php
- lib/RocketMap.php
- lib/RocketMap_MAD.php
I needed a way to show/hide elements on specific geofences.
The only possible way at the moment is to use Boundaries, but it's plain all or nothing.
With this, you can now decide to still show certain elements even if out of your Boundaries using config options :
```
$showPokemonsOutsideBoundaries = false ;
$showGymsOutsideBoundaries = false ;
$showSpawnsOutsideBoundaries = false ;
$showStopsOutsideBoundaries = false ;
```
It won't impact current behaviour if you don't add those options and set them to true. Default is false (as existing).
> Add Options to Show Elements outside of Boundaries

- pre-index.php
A simple change in logic to allow maps without IVs to hide the ExcludeMinIV menu like before the rewrite.
> Hide Pokemon or ExcludeMinIV

- login.php
- static/data/pokemon.json
When authenticating through FB for the first time Access level was being set to 'null' due to access_level being set twice in the insert statement.
> Remove Duplicate access_level in FB Auth

- static/js/map.js
Using MAD since #551 has been merged, the despawn time of the popup was offset and partly outside the popup (see image).
This reworks the css to solve the issue and removes the need for the `left:50px`. It also solves the issue on Firefox and Edge where the confirmed checkmark would wrap to the next line.
Appears to be working correctly on Chrome, Firefox and Edge with and without a value in `firstSeen`. Untested using Safari/iOS.
> fix pokemon despawn time outside of popup

- static/js/map.js
**Issue?**
The background image of nests representing the nest type is broken despite having a valid `nest` key in `config.php` -> `$iconFolderArray`. It could also have other issues down the line.
**Who is affected?**
Anyone running main, staging or develop will experience this issue once they move past #556 which adds the `nest` key to `$iconFolderArray` (config.php).
**Why?**
Only the values of existing keys of `iconsArray` are updating but not the keys themselves after you add, rename or delete a key in `$iconFolderArray` and reload the page.
**About the fix!**
In all current branches, `iconsArray` is an `Object Object`.
Logic wise, removing the `Object String` condition could cause an issue with older pmsf that haven’t upgraded in a while which means you’d need to have `Object …
> fix iconsArray’s keys not updating

- pre-index.php
no reason to display a section with a button that does nothing besides cause a console errors if pressed when the functionality is disabled.
that was the reason I was receiving the below error: it was displaying the functionality on the map while it was disabled in my access-config! (ie confusing for users)
> hide fullStats's section if `$noFullStats = true`

- lib/stats/Stats.rdm.php
- lib/stats/Stats.rocketmap_mad.php
- static/js/stats.js
MAD+RDM: Add costumes to images to be able to differentiate on days where you have both with and without a costume like current Squirtle or different costumes of the same mon. **RDM IS UNTESTED** but it’s a copy/paste from RDM's `query_stops()` to get the value so it should be fine.
MAD+RDM: fix `stardust icon: undefined.png` in console with enableJSDebug enabled. Both MAD and RDM are returning the value in the key `quest_reward_amount` while JavaScript was attempting to use the key `quest_dust_amount`. Both now should display the amounts correctly.
MAD: fix `mega_resource icon: undefined.png` in console with enableJSDebug enabled. MAD wasn't returning the value of `quest_energy_pokemon_id` downstream. Also return the amount to match RDM even through it’s currently unused by getIcon() nor …
> FullStats - Rewards: Misc Adds/Fixes.

- static/js/map.js
While #573 solved the issue of not adding new keys like `nest` that were causing errors, it also caused the styles to be reset to the default value every time the page was loaded.
A condition is added to check for the existence of `iconsArray` in LocalStorage. When it exists (returning user), we only add missing keys to it leaving the rest untouched otherwise we proceed like before fully refreshing `iconsArray`.
> fix style selections not sticking after #573

- pre-index.php
- Some users are reporting `code.createjs.com` as unreachable causing the map loading to fail. PMSF is already using `cdnjs.cloudflare.com` for most of its sources without reported issues so it's the natural move.
- Also pushing soundjs to v1.0.2 which appears to be working fine while also solving ~2 years of bugs between `0.6.2` and `1.0.2`
> change soundjs source + push to v1.0.2

- lib/RDM.php
**ISSUE:**
RDM will be removing the `pvp_rankings_great_league` and `pvp_rankings_ultra_league` columns in favor of a universal `pvp` column which will contain the all pvp leagues (little, great, ultra, etc). Details: <https://github.com/RealDeviceMap/RealDeviceMap/pull/316>
**CHANGE:**
Query the RDM database first to get the `DB_VERSION` which allows the rest of the queries to use the correct pvp column(s) and remain compatible with both the pre and post pvp rework.
> rdm pvp 2.0 support?

- static/js/map.js
fixes this situation:
- WithoutAR successfully scanned
- WithAR not successfully scanned.
- Toggle «With AR-Scan Task» from off to on
- Quest withoutAR is still displayed despite the toggle now being in the withAR position
> always remove and redraw all stops when toggling «With AR-Scan Task»

- lib/RDM.php
- available_slots has been added to rdm master in December 2021.
- availble_slots is being removed from rdm-dev in June 2022.
> rdm: switch from availble_slots to available_slots (gym table)

- lib/RDM.php
- lib/Scanner.php
- lib/stats/Stats.php
- lib/stats/Stats.rdm.php
- optimize the Multi-Incident query for better performance.
- add «columnExists» function to make backward compatibility easier to manage long term and provide better compatibility with forks that may have different `DB_VERSION`.
- add «availble_slots» backward compatibility instead of simply removing the misnamed column so that pmsf can merge to master/staging independently from rdm.
> better incident query, add columnExists and availble_slots compatibility

- static/js/stats.js
- both mad and rdm are populating `['form']` with intvar() so a strict comparison (`int===str`) cannot work.
> fix sidebar pokemons that had partial results

- static/js/map.common.js
- level is only directly present on rdm but BOTH backend will do some calculations (rdm: unencountered, mad: all) which makes it a less optimal choice.
- atk/def/sta are present on both backend, already passed to the function and require no extra calculations which makes it the better choice.
> logic change for 0%iv shadow

- pre-index.php
- raw_data.php
- previously only used for manual submissions.
- pokémon filter, notification filter and mons queries should now respect it.
- only added to `$eids` if actually populated to avoid affecting performance when unused.
No config change. Examples if you wish to use it in your config/access-config:
```
Don’t exclude anything (default):
$pokemonToExclude = [];
Exclude id 1, 2, 3 and 4:
$pokemonToExclude = [1, 2, 3, 4];
Exclude everything except id 1, 2, 3 and 4:
$pokemonToExclude = array_diff(range(1, $numberOfPokemon), [1, 2, 3, 4]);
```
> make `$pokemonToExclude` work with mad and rdm for mons

- lib/RDM.php
- lib/RocketMap_MAD.php
- static/js/map.js
- static/js/stats.js
- despawn_sec(RDM) and calc_endminsec(MAD) both default to `null` when unknown.
- code used `intval(column) ` which resulted in 0 if `null` or despawn time was exactly `0:00` making them impossible to distinguish and displayed `Unknown spawnpoint info` for `0:00` known despawn time.
- code will now set it to `null` when unknown and intval(column) if not null.
> fix: make spawnpoint despawn time of 0:00 and unknown(null) distinguishable

- .eslintrc.json
- config/default.php
- config/example.config.php
- lib/RDM.php
- lib/RocketMap_MAD.php
- pre-index.php
- static/js/map.common.js
- static/js/map.js
- display ranks in mons popup
- add LLR filter to menu (LittleLeagueRank)
- reset to no filtering when `$noMinXXRank` is true to prevent users from being stuck with invisible filtering when admin changes `$noMinXXRank` from false to true
new config variables
- `$noMinLLRank`. Default: `false` (enabled)
- `$minLLRank`. Default `0` (no filtering)
> add little league support (rdm only)

- lib/RocketMap_MAD.php
- without that field, the weather reported on the map was correct but it was always marked as «Out Of Date» with an invalid date
> fix: mad weather query was not selecting `last_updated`

- .eslintrc.json
- config/default.php
- config/example.config.php
- lib/RDM.php
- lib/RocketMap.php
- lib/RocketMap_MAD.php
- pre-index.php
- raw_data.php
- static/js/map.common.js
- static/js/map.js
- allows users to display 0%IV mons on the map regardless of the value used in the MinIV, MinLVL, MinLLR, MinGLR or MinULR filters.
new config variables
- `$noZeroIvToggle`. Default: `false` (enabled)
> add 0%iv toggle to pokemon menu

- .eslintrc.json
- config/default.php
- config/example.config.php
- lib/RDM.php
- lib/RocketMap.php
- lib/RocketMap_MAD.php
- pre-index.php
- raw_data.php
- static/js/map.common.js
- static/js/map.js
- allows users to display 100%IV mons on the map regardless of the value used in the MinIV, MinLVL, MinLLR, MinGLR or MinULR filters.
new config variables
- `$noHundoIvToggle`. Default: `false` (enabled)
> add 100%iv toggle to pokemon menu

- .eslintrc.json
- config/default.php
- config/example.config.php
- lib/RDM.php
- pre-index.php
- static/js/map.js
- any pvp rankings that does not pass either of those global limits will be discarded. They will fail any pvp checks and will never be displayed to the user.
- if «$globalRankLimitXX» is set to 0, the limit will be the user’s current filter setting in his UI. Ex: user has his filter set to 3/3/3, it will only try to match ranks 1 to 3, only display ranks 1 to 3 and discard any rankings from 4 to 4096.
- if «$globalRankLimitXX» is set to 1000, it will only try to match ranks 1 to 1000, only display ranks 1 to 1000 and discard any rankings from 1001 to 4096.
- add optional «[Cap XX]» text in popup to provide clarity for different ranks with same cp, level and mons that can occur when using multiple level caps calculations.
- to preserve pmsf’s current behavior, the defaults are set to not …
> add global per league pvp filter for cp and rank

- lib/RDM.php
- lib/Scanner.php
- lib/stats/Stats.php
- lib/stats/Stats.rdm.php
- solves issue that can occur when the `grunt_type` column is not deleted from the `pokestop` table during the rdm migration.
- improve `columnExists()`
> check existence of new column instead of old one (rdm incidents)

- lib/RDM.php
- lib/RocketMap_MAD.php
- lib/search/Search.rdm.php
- lib/search/Search.rocketmap_mad.php
- lib/stats/Stats.rdm.php
- lib/stats/Stats.rocketmap_mad.php
- better for query performance.
- rdm has had auto-generated columns for a while so json_extracts no longer make sense.
- mad now uses `quest_stardust` for xp and dust amounts in both master(PR#1273) and async(PR#1272).
> use columns instead of json_extract when possible

- login.php
- `$guilds` can be retrieved data from Discord which is not always as expected.
- should solve the following error that sometimes occurred when that happened.
```
PHP Warning:  array_column() expects parameter 1 to be array, null given in /var/www//html/login.php on line 670, referer: https://**/?login=true
PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/*/html/login.php on line 670, referer: https://**/?login=true
```
> extra validation to Discord login

- lib/RDM.php
- lib/stats/Stats.rdm.php
- #749 may not work as intended in some scenarios (duplicates).
- this should work as intended based the current knowledge about multiple invasion.
- the better solution is a more complex subquery or 2 queries processed in php but the performance impact of either solution is too big on larger incident tables while providing no benefit if current knowledge doesn’t change.
- the final solution would be full support for multiple invasions but it’s not possible right now.
> better solution than #749

- lib/RDM.php
- lib/stats/Stats.rdm.php
- The left join worked as intended for raw_data refreshes on smaller setups but it was just too expansive and slow on larger setups for a query that runs every few seconds. The left join has been simplified to the minimum required to join the tables which improves backend performance on all setups (query+php).
- FullStats: the query to gather the stop statistics was slow due to the same left join. An alternate method is now used which allows the removal of the left join and make the query more performant.
> move incident deduping from left join to php

- lib/RDM.php
- lib/RocketMap_MAD.php
- utils.php
- empty string works down to at least 7.4 which goes past End Of Life in Nov 2022
- also `$message` was declared properly before being `.=`
> DateTime -> Passing null to is deprecated in php 8.1

- lib/RocketMap_MAD.php
- this follows the hacky mad implementation of using a random grunt_id instead of following the actual protos.
> mad: add Kecleon support (EventStops)

- config/default.php
- config/example.config.php
- filterimages.php
- static/data/moves.json
- static/data/pokemon.json
- push max pokemon to 1008
- gen 9 mons added up to 1008 (pokemon.json)
- add `generation9` and `paldea` keywords
- add 2 moves: Boomburst + Double Iron Bash (moves.json)
> add gen 9 support + update json

- login.php
- Assuming it's exclusive to Facebook login since parse_signed_request() always returns null without $facebookAppSecret.
- parse_signed_request() has been removed by Willem's initial PR.
> more leftovers

- lib/RDM.php
- lib/RocketMap.php
- lib/RocketMap_MAD.php
- static/js/map.js
- utils.php
- use UICONS shadow icons if available for raids (_a1)
- add "Shadow" to popup if `raid_level` is 11-15 or `raid_pokemon_alignment` = 1
- cut down on # of stars in popup (Raid *********** -> Raid Shadow *)
> add support for `raid_pokemon_alignment`
